image: registry.gitlab.dev-o-sud.fr/public-devosud/docker-images/flutter:latest

stages:
  - analyze
  - build
  - test
  - deploy

analyze:flutter:
  stage: analyze
  script:
    - flutter analyze
  tags:
    - flutter

build:android:
  stage: build
  script:
    - echo "$KEYSTORE" | base64 --decode > ./android/app/keystore.jks
    - echo "storePassword=$STORE_PASSWORD" > ./android/key.properties
    - echo "keyPassword=$KEY_PASSWORD" >> ./android/key.properties
    - echo "keyAlias=$KEY_ALIAS" >> ./android/key.properties
    - echo "storeFile=./keystore.jks" >> ./android/key.properties
    - cat $GOOGLE_SERVICES >> ./android/app/google-services.json
    - flutter build apk --split-per-abi
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-arm64-v8a-release.apk
    expire_in: 1 days
  tags:
    - flutter

test:flutter:
  stage: test
  script:
    - flutter test
  tags:
    - flutter

deploy:android:
  stage: deploy
  script:
    - firebase appdistribution:distribute build/app/outputs/apk/release/app-arm64-v8a-release.apk --app "$APP_ID" --release-notes-file release_notes.txt --groups-file groups_file.txt
  tags:
    - flutter
  only:
    - tags

