name: carg
description: Get coinched !

version: 0.6.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  algolia: ^0.1.7
  cloud_firestore: ^0.14.1+2
  cupertino_icons: ^1.0.0
  enum_to_string: ^1.0.9
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.0+4
  intl: ^0.16.1
  package_info: ^0.4.1
  pedantic: ^1.8.0
  provider: ^4.1.2
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/images/search_by_algolia.png
    - assets/config/

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png
