name: Flutter - Build
on:
  push:
    branches:
      - master
jobs:
  analyze:
    name: Analyze Flutter
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2.3.2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '11'
      - name: 'Set up Flutter (last stable)'
        uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'stable'
      - name: 'Analyze code'
        run: flutter analyze
  build_apk:
    needs: analyze
    name: 'Build Flutter (Android)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2.3.2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '11'
      - name: 'Set up Flutter (last stable)'
        uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'stable'
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: 'Build APK'
        run: flutter build apk --split-per-abi
        shell: 'bash'
      - name: 'Save APK'
        uses: actions/upload-artifact@v2
        with:
          name: 'apk-build'
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk