name: Default workflow

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'The Flutter version used used (ex: 2.5.1)'
        required: true
        type: string
        default: '2.8.1'
      android_output:
        description: 'Android build file type output (apk or abb)'
        required: true
        type: choice
        default: 'apk'
        options:
          - 'apk'
          - 'abb'
    branches-ignore:
      - main
      - dev

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: ${{ inputs.flutter_version }}
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: ${{ inputs.flutter_version }}
      android_output: ${{ inputs.android_output }}
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}