name: Default workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '2.8.1'
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '2.8.1'
      android_output: 'apk'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}