name: Default workflow

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '3.16.5'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
  functions:
    uses: ./.github/workflows/functions.action.yaml
    with:
      deploy: false
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '3.16.5'
      android_output: 'apk'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}