name: Dev workflow

on:
  push:
    paths:
      - 'firebase_functions/**'
    branches:
      - dev

jobs:
  functions:
    uses: ./.github/workflows/functions.action.yaml
    with:
      deploy: true
    secrets: inherit