name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '3.0.5'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
  functions:
    uses: ./.github/workflows/functions.action.yaml
    with:
      deploy: true
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}
  hosting:
    uses: ./.github/workflows/hosting.action.yaml
    secrets:
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '3.0.5'
      android_output: 'aab'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
  fastlane-dry-run:
    needs: [ flutter-build ]
    uses: ./.github/workflows/fastlane.action.yaml
    with:
      lane: 'dry_run'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}