name: Firebase deploy hosted websites

on:
  workflow_call:
    inputs:
      lane:
        description: 'Lane version (beta, or production)'
        required: true
        type: string
    secrets:
      passphrase:
        description: 'The passphrase to decrypt the configuration'
        required: true
      firebase_token:
        description: 'Token used by firebase login'
        required: true


jobs:
  build_deploy:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.passphrase }}
      - name: 'Setup Node / NPM'
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install -g firebase-tools
      - name: 'Deploy hosting - beta'
        if: ${{ inputs.lane == 'beta' }}
        run: |
          cd ./firebase_hosting
          firebase deploy hosting:channel:deploy beta
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
      - name: 'Deploy hosting - production'
        if: ${{ inputs.lane == 'production' }}
        run: |
          cd ./firebase_hosting
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}