name: Flutter - CI (firebase app distribution)
on:
  push:
    tags:
      - v*
  release:
    types: [published]

jobs:
  analyze:
    name: 'Analyze'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Analyze code'
        run: flutter analyze
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Analyze code'
        run: flutter test
  build_android:
    needs: [ analyze, test ]
    name: 'Build Android'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: 'Build APK'
        run: flutter build apk --split-per-abi --dart-define=FLAVOR=prod
        shell: 'bash'
      - name: 'Save APK'
        uses: actions/upload-artifact@v2
        with:
          name: 'apk-build'
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
  deploy_android:
    needs: build_android
    name: 'Upload APK on Firebase'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2.3.2
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: 'apk-build'
      - name: 'Deploy to Firebase'
        run: firebase appdistribution:distribute --token "$FIREBASE_TOKEN" app-arm64-v8a-release.apk --app "$APP_ID" --release-notes-file CHANGELOG.md --groups-file groups_file.txt
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
