name: Tag workflow

on:
  push:
    tags:
      - v*

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '2.10.3'
  functions:
    uses: ./.github/workflows/functions.action.yaml
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
      firebase_token: ${{ secrets.FIREBASE_TOKEN }}
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '2.10.3'
      android_output: 'aab'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
  fastlane:
    needs: [flutter-build]
    uses: ./.github/workflows/fastlane.action.yaml
    with:
      lane: 'beta'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}